AWSTemplateFormatVersion: '2023-07-10'
Transform: AWS::Serverless-2023-07-30
Description: Musify Springboot Application with Lambda.

Resources:
  LambdaSpringBootFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.musify.lambda.LambdaHandler::handleRequest
      Runtime: java11
      CodeUri: target/musify-0.0.1-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  LambdaSpringBootApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/musify/music-artist/details'
    Export:
      Name: Musify